# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ecbbb03f1ad3b108e0d737235859727a0dac114c5f20abaf2941c3df5efe52b33d0e05c91102bf85065152cd5acc3d02f842db9ae6cad03cb24ab2b5814732

test:
  secret_key_base: df6efea244048ddb75089094adb9c6827a9757a6b5cc28ff726aa95bb6965eb4e824f06a8766789cca6ad572e1ddb16e7eafeebe3e257abe056d8d7f92c0adb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
